import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import NavBar from '../components/NavBar'
import "./globals.css";



const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
});



export const metadata: Metadata = {
  title: "Skinstric",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased relative overflow-hidden tracking-tighter text-[#1a1b1c]`}
      >
        <NavBar />
        <section className="mt-18.75 min-h-[calc(100vh-75px)]">

    {children}
    </section>
      </body>
    </html>
  );
}
